// <auto-generated />
namespace ExamReg.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class themTitlechoLophp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themTitlechoLophp));
        
        string IMigrationMetadata.Id
        {
            get { return "201911030858444_themTitlechoLophp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
