// <auto-generated />
namespace ExamReg.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class addStatustoSV_LT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStatustoSV_LT));
        
        string IMigrationMetadata.Id
        {
            get { return "201911251534274_addStatustoSV_LT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
